### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by fil1089** [laps78/VK-friends-auto-add#2]
Both the extension and the script stopped working

**Comment by laps78** [comment]
Thanks, fil1089!
I see the problem and what it comes from. 

VK has it's UI updated so I need some time to update the script & the extension.
I hope I get this done by next week...

**Comment by fil1089** [comment]
Евгений, здравствуйте. Я там сам немного со скриптом пошаманил, если хотите
могу скинуть

Чт, 7 нояб. 2024 г. в 14:09, Евгений L.A.P.S. Лаптев <
***@***.***>:

**Comment by laps78** [comment]
All fixed 
thanks
